# Copyright 2019 the Tectonic Project
# Licensed under the MIT License.

jobs:

- job: custom_cross
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
    - script: |
        docker build -t tectonictypesetting/ttcross:${{ parameters.tag }} custom-cross/
        docker tag tectonictypesetting/ttcross:${{ parameters.tag }} tectonictypesetting/ttcross:latest
      displayName: Build ttcross Docker image

    - task: Docker@2
      displayName: ALWAYS Push image to Hub
      inputs:
        command: push
        containerRegistry: pkgw@DockerHub
        repository: tectonictypesetting/ttcross
        tags: |
          ${{ parameters.tag }}
          latest
