# Copyright 2019 the Tectonic Project
# Licensed under the MIT License.

# DO NOT MERGE CHECKING IF DOCKER BUILDX CAN WORK

trigger:
  branches:
    exclude:
    - '*'

pr:
  branches:
    include:
    - master
  paths:
    include:
    - custom-cross/

variables:
- template: variables.yml

jobs:
- job: test_buildx
  pool:
    vmImage: ${{ variables.linux_image }}

  steps:
  - script: |
      set -xeuo pipefail
      mkdir -p ~/.docker/cli-plugins
      curl -fsSL "$URL" >$HOME/.docker/cli-plugins/docker-buildx
      chmod +x $HOME/.docker/cli-plugins/docker-buildx
    env:
      URL: https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
    displayName: Install docker-buildx
  - script: |
      set -xeuo pipefail
      docker buildx create --use --name insecure-builder --buildkitd-flags '--allow-insecure-entitlement security.insecure'
      docker buildx build --allow security.insecure -t test custom-cross/TEST/
    displayName: test Docker
